# Generated by Django 5.1 on 2024-08-29 13:02

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0004_rename_images_pods_gallery_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=15, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("post_code", models.CharField(max_length=10)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank="(Select country)", max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("number_of_guests", models.PositiveIntegerField()),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.pods"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakeBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "booking_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.bookingdetails",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.guestdetails",
                    ),
                ),
            ],
        ),
    ]
