# Generated by Django 5.1 on 2024-08-29 13:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestdetails",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="GB"
            ),
        ),
    ]
