# Generated by Django 5.1 on 2024-08-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_guestdetails_contact_number"),
        ("home", "0004_rename_images_pods_gallery_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makebooking",
            name="booking_details",
        ),
        migrations.RemoveField(
            model_name="makebooking",
            name="guest",
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("number_of_guests", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("arrived", "Arrived"),
                            ("departed", "Departed"),
                            ("completed", "Completed"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.guestdetails",
                    ),
                ),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.pods"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BookingDetails",
        ),
        migrations.DeleteModel(
            name="MakeBooking",
        ),
    ]
