# Generated by Django 5.1 on 2024-08-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_makebooking_booking_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestdetails",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
