# Generated by Django 4.1.7 on 2024-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pods",
            name="couches",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
