# Generated by Django 4.1.7 on 2024-08-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_pods_couches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pods",
            name="price",
        ),
        migrations.RemoveField(
            model_name="pods",
            name="rating",
        ),
        migrations.AddField(
            model_name="pods",
            name="facilitiess",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
