# Generated by Django 5.1 on 2024-08-27 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_pods_price_remove_pods_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pods",
            old_name="images",
            new_name="gallery_images",
        ),
    ]
