# Generated by Django 5.1 on 2024-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_pods_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pods",
            name="status",
        ),
        migrations.AddField(
            model_name="pods",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
