# Generated by Django 5.1 on 2024-09-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_pods_status_pods_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pods",
            name="gallery_images",
        ),
        migrations.CreateModel(
            name="PodImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pod_images/"),
                ),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="home.pods",
                    ),
                ),
            ],
        ),
    ]
