# Generated by Django 5.1 on 2024-09-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_pods_pod_images_pods_pod_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pods",
            name="pod_images",
        ),
        migrations.AddField(
            model_name="podimages",
            name="pod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="home.pods",
            ),
        ),
    ]
